###
GET http://localhost:3000/matches

###
GET http://localhost:3000/matches/M002

####
POST http://localhost:3000/matches
Content-Type: application/json

{
  "Match_ID": "M001",
    "Date": "2024-02-08",
    "Score": "2-0",
    "Stadium": "Standford Bridge",
    "Goals":  [
        { "Player_ID": "P003", "Time": "30" },
        { "Player_ID": "P004", "Time": "75" }
            ],
     "Teams_Involved": ["CHE", "MAN"]
    },
  

###
PUT http://localhost:3000/matches
Content-Type: application/json

{
  "Match_ID": "M001",
    "Date": "2024-02-08",
    "Score": "2-0",
    "Stadium": "Standford Bridge",
    "Goals":  [
        { "Player_ID": "P003", "Time": "30" },
        { "Player_ID": "P004", "Time": "75" }
            ],
     "Teams_Involved": ["CHE", "MAN"]
    
}

###
DELETE http://localhost:3000/matches/M092



###
GET https://.onrender.com/matches

###
GET https://.onrender.com/matches/M002

###
POST https://.onrender.com/matches
Content-Type: application/json

{
  "Match_ID": "M001",
    "Date": "2024-02-08",
    "Score": "2-0",
    "Stadium": "Standford Bridge",
    "Goals":  [
        { "Player_ID": "P003", "Time": "30" },
        { "Player_ID": "P004", "Time": "75" }
            ],
     "Teams_Involved": ["CHE", "MAN"]
    
}



###
PUT https://.onrender.com/matches/M099
Content-Type: application/json

{
    "Match_ID": "M001",
    "Date": "2024-02-01",
    "Score": "2-0",
    "Stadium": "Standford Bridge",
    "Goals":  [
        { "Player_ID": "P003", "Time": "30" },
        { "Player_ID": "P004", "Time": "75" }
            ],
     "Teams_Involved": ["CHE", "MAN"]
}

###
DELETE https://.onrender.com/matches/M099