###
GET http://localhost:3000/players

###
GET http://localhost:3000/Players/P002

###
GET http://localhost:3000/Players/P004

###
GET http://localhost:3000/players/Position/Midfielder

####
POST http://localhost:3000/players
Content-Type: application/json

{
      "Player_ID": "P004",
      "Name": "Mohamed Salah",
      "Age": 29,
      "Height": 175,
      "Nationality": "Egypt",
      "Position": "Forward",
      "Team_ID": "LIV"
}

###
PUT http://localhost:3000/players/P002
Content-Type: application/json

{
      "Player_ID": "P002",
      "Name": "Mason Mount",
      "Age": 23,
      "Height": 180,
      "Nationality": "England",
      "Position": "Midfielder",
      "Team_ID": "CHE"
}

###
DELETE http://localhost:3000/players/P002



###
GET https://teamsoccerapi.onrender.com/players

###
GET https://teamsoccerapi.onrender.com/players/P002

###
GET https://teamsoccerapi.onrender.com/players/

###
POST https://teamsoccerapi.onrender.com/players/Midfielder
Content-Type: application/json

{
      "Player_ID": "P002",
      "Name": "Mason Mount",
      "Age": 23,
      "Height": 180,
      "Nationality": "England",
      "Position": "Midfielder",
      "Team_ID": "CHE"
}


###
PUT https://teamsoccerapi.onrender.com/players/P002
Content-Type: application/json

{
      "Player_ID": "P006",
      "Name": "Phil Foden",
      "Age": 21,
      "Height": 171,
      "Nationality": "England",
      "Position": "Midfielder",
      "Team_ID": "MCI"
}

###
DELETE https://teamsoccerapi.onrender.com/players/P002